Repository dotnet/runtimelab, pull requests merged in 2020-12, with the labels that each got.

#367 Add analyzer to flag converting from DllImport to GeneratedDllImport
  DllImportGenerator/Demo/.editorconfig
  DllImportGenerator/DllImportGenerator.UnitTests/ConvertToGeneratedDllImportAnalyzerTests.cs
  DllImportGenerator/DllImportGenerator.UnitTests/Verifiers/CSharpAnalyzerVerifier.cs
  DllImportGenerator/DllImportGenerator/AnalyzerReleases.Unshipped.md
  DllImportGenerator/DllImportGenerator/Analyzers/AnalyzerDiagnostics.cs
  DllImportGenerator/DllImportGenerator/Analyzers/ConvertToGeneratedDllImportAnalyzer.cs
  DllImportGenerator/DllImportGenerator/Resources.Designer.cs
  DllImportGenerator/DllImportGenerator/Resources.resx
Labels: area-DllImportGenerator

#413 Make JsonSerializableAttribute applicable to assembly, not module
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.Tests/JsonSourceGeneratorTests.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.Tests/TestClasses.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.UnitTests/CompilationHelper.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.UnitTests/JsonSourceGeneratorDiagnosticsTests.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.UnitTests/JsonSourceGeneratorTests.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.UnitTests/TypeWrapperTests.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/JsonSourceGenerator.cs
  src/libraries/System.Text.Json/ref/System.Text.Json.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Attributes/JsonSerializableAttribute.cs
  src/libraries/System.Text.Json/tests/Serialization/JsonSerializableTypes.cs
Labels: area-JsonCodeGen

#384 Reliability improvements for array marshalling
  DllImportGenerator/DllImportGenerator/ArrayMarshallingCodeContext.cs
  DllImportGenerator/DllImportGenerator/Marshalling/BlittableArrayMarshaller.cs
  DllImportGenerator/DllImportGenerator/Marshalling/ConditionalStackallocMarshallingGenerator.cs
  DllImportGenerator/DllImportGenerator/Marshalling/NonBlittableArrayMarshaller.cs
Labels: area-DllImportGenerator

#427 Refactor default converter registration to allow trimming when converters not used
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/JsonSourceGeneratorHelper.cs
  src/libraries/System.Text.Json/ref/System.Text.Json.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/NullableConverterFactory.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonResumableConverterOfT.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Span.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.ByteArray.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Stream.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Utf8JsonWriter.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerContext.Known.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerContext.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonClassInfo.Cache.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonClassInfo.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonObjectInfoOfT.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/KnownCollectionTypeInfos.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/KnownDictionaryTypeInfos.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReflectionMemberAccessor.cs
  src/libraries/System.Text.Json/tests/Serialization/Array.ReadTests.cs
  src/libraries/System.Text.Json/tests/Serialization/Array.WriteTests.cs
  src/libraries/System.Text.Json/tests/Serialization/OptionsTests.cs
Labels: area-JsonCodeGen

#435 Fix conditions for implicit use of hardware intrinsics
  src/coreclr/src/ToolBox/superpmi/superpmi-shared/icorjitinfoimpl.h
  src/coreclr/src/ToolBox/superpmi/superpmi-shim-collector/icorjitinfo.cpp
  src/coreclr/src/ToolBox/superpmi/superpmi-shim-counter/icorjitinfo.cpp
  src/coreclr/src/ToolBox/superpmi/superpmi-shim-simple/icorjitinfo.cpp
  src/coreclr/src/ToolBox/superpmi/superpmi/icorjitinfo.cpp
  src/coreclr/src/inc/corinfo.h
  src/coreclr/src/jit/ICorJitInfo_API_wrapper.hpp
  src/coreclr/src/jit/compiler.cpp
  src/coreclr/src/jit/compiler.h
  src/coreclr/src/jit/hwintrinsic.cpp
  src/coreclr/src/jit/namedintrinsiclist.h
  src/coreclr/src/tools/Common/JitInterface/CorInfoBase.cs
  src/coreclr/src/tools/Common/JitInterface/CorInfoImpl.cs
  src/coreclr/src/tools/Common/JitInterface/ThunkGenerator/ThunkInput.txt
  src/coreclr/src/tools/aot/ILCompiler.Compiler/Compiler/HardwareIntrinsicHelpers.Aot.cs
  src/coreclr/src/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs
  src/coreclr/src/tools/aot/ILCompiler/Program.cs
  src/coreclr/src/tools/aot/jitinterface/jitinterface.h
  src/coreclr/src/vm/jitinterface.cpp
  src/coreclr/src/vm/jitinterface.h
  src/coreclr/src/zap/zapinfo.cpp
  src/coreclr/src/zap/zapinfo.h
  src/tests/nativeaot/SmokeTests/HardwareIntrinsics/Program.cs
Labels: area-NativeAOT

#423 Update prefix of packages and published assemblies
  DllImportGenerator/Ancillary.Interop/Ancillary.Interop.csproj
  DllImportGenerator/Demo/Program.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/ArrayTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/BlittableStructTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/BooleanTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/CharacterTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/Constants.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/CustomMarshallingTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/DelegateTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/EnumTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/PointerTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/PreserveSigTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/SafeHandleTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/SetLastErrorTests.cs
  DllImportGenerator/DllImportGenerator.IntegrationTests/StringTests.cs
  DllImportGenerator/DllImportGenerator/DllImportGenerator.csproj
  DllImportGenerator/TestAssets/NativeExports/NativeExports.csproj
  DllImportGenerator/Tools/Benchmarking/Benchmarking.csproj
  DllImportGenerator/Tools/PInvokeDump/PInvokeDump.csproj
Labels: area-DllImportGenerator

#379 Support arrays of types with simple custom marshalling
  DllImportGenerator/DllImportGenerator.IntegrationTests/ArrayTests.cs
  DllImportGenerator/DllImportGenerator.UnitTests/CodeSnippets.cs
  DllImportGenerator/DllImportGenerator.UnitTests/CompileFails.cs
  DllImportGenerator/DllImportGenerator.UnitTests/Compiles.cs
  DllImportGenerator/DllImportGenerator/ArrayMarshallingCodeContext.cs
  DllImportGenerator/DllImportGenerator/Marshalling/BlittableArrayMarshaller.cs
  DllImportGenerator/DllImportGenerator/Marshalling/MarshallingGenerator.cs
  DllImportGenerator/DllImportGenerator/Marshalling/NonBlittableArrayMarshaller.cs
  DllImportGenerator/DllImportGenerator/MarshallingAttributeInfo.cs
  DllImportGenerator/DllImportGenerator/Resources.Designer.cs
  DllImportGenerator/DllImportGenerator/Resources.resx
  DllImportGenerator/DllImportGenerator/StubCodeContext.cs
  DllImportGenerator/DllImportGenerator/TypePositionInfo.cs
  DllImportGenerator/TestAssets/NativeExports/Arrays.cs
  DllImportGenerator/designs/Compatibility.md
Labels: area-DllImportGenerator

#445 Fix reproNative
  src/coreclr/tools/aot/ILCompiler/reproNative/reproNative.vcxproj
Labels: area-NativeAOT

#444 Do not require ILProvider in UsageBasedMetadataManager
  src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/CodeBasedDependencyAlgorithm.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReflectableMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ScannedMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/StringAllocatorMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/GeneratingMetadataManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/MetadataManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UsageBasedMetadataManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/DependencyAnalysis/MethodCodeNode.cs
  src/coreclr/tools/aot/ILCompiler/Program.cs
Labels: area-NativeAOT

#456 Fix Checked multifile builds
  src/tests/run.proj
Labels: area-NativeAOT

#422 Add support for feature switches
  src/coreclr/Directory.Build.targets
  src/coreclr/nativeaot/System.Private.CoreLib/System.Private.CoreLib.csproj
  src/coreclr/tools/Common/TypeSystem/IL/ILReader.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ScannerExtensions.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/FeatureSwitchManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ProcessLinkerXmlBase.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/ILCompiler.Compiler.csproj
  src/coreclr/tools/aot/ILCompiler/Program.cs
  src/tests/nativeaot/SmokeTests/FeatureSwitches/FeatureSwitches.cs
  src/tests/nativeaot/SmokeTests/FeatureSwitches/FeatureSwitches.csproj
  src/tests/nativeaot/SmokeTests/FeatureSwitches/ILLink.Substitutions.xml
Labels: area-NativeAOT

#461 Static linking for System.Compression.Native on Windows
  eng/liveBuilds.targets
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.props
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Windows.props
  src/libraries/Native/Windows/CMakeLists.txt
  src/libraries/Native/Windows/System.IO.Compression.Native/CMakeLists.txt
Labels: area-NativeAOT

#463 Align library feature settings with IL Linker
  docs/using-nativeaot/optimizing.md
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets
Labels: area-NativeAOT

#459 Populate list of Windows APIs that are safe to direct call
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Windows.props
  src/coreclr/nativeaot/BuildIntegration/WindowsAPIs.txt
Labels: area-NativeAOT

#470 Eliminate CORERT ifdef
  src/coreclr/nativeaot/System.Private.CoreLib/src/Resources/Strings.resx
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Delegate.cs
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/MulticastDelegate.cs
  src/libraries/System.Private.CoreLib/src/System/Delegate.cs
Labels: area-NativeAOT

#471 Couple fixes to repro project rsp file
  src/coreclr/tools/aot/ILCompiler/repro/repro.csproj
Labels: area-NativeAOT

#472 Sync shared IL Linker files
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReferenceSource/README.md
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReferenceSource/ReflectionMethodBodyScanner.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs
Labels: area-NativeAOT

#473 Fix logging in the absence of symbols
  src/coreclr/tools/Common/Compiler/DisplayNameHelpers.cs
  src/coreclr/tools/Common/Compiler/Logger.cs
  src/coreclr/tools/Common/Compiler/Logging/MessageContainer.cs
  src/coreclr/tools/Common/Compiler/Logging/MessageOrigin.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/ILCompiler.Compiler.csproj
Labels: area-NativeAOT

#478 Report the source for this parameter as "the method"
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ValueNode.cs
Labels: area-NativeAOT

#488 Substitute IsDynamicCodeSupported/Compiled as always false
  src/coreclr/nativeaot/System.Private.CoreLib/System.Private.CoreLib.csproj
  src/coreclr/nativeaot/System.Private.CoreLib/src/ILLink/ILLink.Substitutions.xml
Labels: area-NativeAOT

#489 Don't allow generic inlining if context differs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/DictionaryLayoutNode.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs
  src/tests/nativeaot/SmokeTests/Generics/Generics.cs
Labels: area-NativeAOT

#496 Try to fix Pri-0 test runs
  eng/pipelines/runtimelab/coreclr-tests.yml
Labels: area-NativeAOT

#493 Generic virtual method analysis tweaks
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ConstructedEETypeNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/GVMDependenciesNode.cs
Labels: area-NativeAOT

#498 NOP out bytes in unreachable basic blocks
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/FeatureSwitchManager.cs
Labels: area-NativeAOT

#480 Disable BinaryFormatter by default
  docs/using-nativeaot/optimizing.md
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets
Labels: area-NativeAOT

#507 Fix custom attribute metadata processing
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/AnalysisBasedMetadataManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/CustomAttributeBasedDependencyAlgorithm.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/CustomAttributeMetadataNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UsageBasedMetadataManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/ILCompiler.Compiler.csproj
  src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/IMetadataPolicy.cs
  src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs
Labels: area-NativeAOT

#506 Generate new debug info for methods with substituted code
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/FeatureSwitchManager.cs
Labels: area-NativeAOT

#510 Respect ILLink annotations to remove custom attributes
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/CustomAttributeBasedDependencyAlgorithm.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ProcessLinkerXmlBase.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UsageBasedMetadataManager.cs
  src/coreclr/tools/aot/ILCompiler/Program.cs
Labels: area-NativeAOT

#509 Add a couple more things under FEATURE_UNIVERSAL_GENERICS
  src/coreclr/nativeaot/System.Private.TypeLoader/src/Internal/Runtime/TypeLoader/GenericDictionaryCell.cs
  src/coreclr/nativeaot/System.Private.TypeLoader/src/Internal/Runtime/TypeLoader/TypeBuilder.cs
Labels: area-NativeAOT
