Repository dotnet/runtimelab, pull requests merged in 2021-02, with the labels that each got.

#617 Fix one of the AOT warnings in EventSource
  src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/PropertyValue.cs
Labels: area-NativeAOT

#619 Make it possible to disable non-filestream support in XmlDownloadManager
  src/coreclr/nativeaot/System.Private.CoreLib/src/Internal/Runtime/CompilerHelpers/ThrowHelpers.cs
  src/coreclr/nativeaot/System.Private.CoreLib/src/Resources/Strings.resx
  src/libraries/System.Private.Xml/src/ILLink/ILLink.Substitutions.xml
Labels: area-NativeAOT

#623 Fix another AOT warning in TraceLogging
  src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/PropertyValue.cs
Labels: area-NativeAOT

#624 Limit the overhead of ValueType.Equals/GetHashCode support
  src/coreclr/tools/Common/TypeSystem/IL/Stubs/ValueTypeGetFieldHelperMethodOverride.cs
  src/coreclr/tools/Common/TypeSystem/IL/TypeSystemContext.ValueTypeMethods.cs
Labels: area-NativeAOT

#628 Move TypePreinit construction into try/catch
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/TypePreinit.cs
Labels: area-NativeAOT

#627 Suppress AOT warning in `Sizeof<T>`
  src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs
Labels: area-NativeAOT

#629 Optimize Thread.CurrentThread.ManagedThreadId
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.CoreRT.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/JitHelper.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs
Labels: area-NativeAOT

#636 Ifdef EventSource validation that looks at IL bodies
  src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs
Labels: area-NativeAOT

#620 Limit impact of `typeof()` in a custom attribute
  src/coreclr/nativeaot/System.Private.Reflection.Execution/src/Internal/Reflection/Execution/PayForPlayExperience/MissingMetadataExceptionCreator.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/CustomAttributeBasedDependencyAlgorithm.cs
  src/tests/nativeaot/SmokeTests/Reflection/Reflection.cs
Labels: area-NativeAOT

#588 Anchorsupdate
  src/libraries/System.Text.RegularExpressions/ref/System.Text.RegularExpressions.cs
  src/libraries/System.Text.RegularExpressions/src/System.Text.RegularExpressions.csproj
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Match.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.Match.SRM.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexCompiler.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexNode.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexOptions.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/AutomataException.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/Match.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/Regex.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/RegexOptions.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/RegexToAutomatonConverter.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/State.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/SymbolicRegexBuilder.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/SymbolicRegexInfo.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/SymbolicRegexNode.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BDD.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BDDAlgebra.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BV.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BV64Algebra.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BVAlgebra.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/CharSetSolver.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/CharacterEncoding.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/IBooleanAlgebra.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/ICharAlgebra.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/IntervalSet.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/MintermGenerator.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/RangeConverter.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/BooleanDecisionTree.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/DecisionTree.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/IMatcher.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/SymbolicRegexMatcher.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/UTF8Encoding.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/VectorizedIndexOf.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/printing/RegexCharSetPrinter.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/unicode/IgnoreCaseRelation.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/unicode/IgnoreCaseRelationGenerator.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/unicode/IgnoreCaseTransformer.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/unicode/UnicodeCategoryRanges.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/unicode/UnicodeCategoryRangesGenerator.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/unicode/UnicodeCategoryTheory.cs
  src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/utils/StringUtility.cs
  src/libraries/System.Text.RegularExpressions/tests/RegexSRMTests.cs
  src/libraries/System.Text.RegularExpressions/tests/System.Text.RegularExpressions.Tests.csproj
Labels: area-RegexSRM

#646 Add support for MarshalStructure in RD.XML
  docs/using-nativeaot/rd-xml-format.md
  src/coreclr/tools/aot/ILCompiler/RdXmlRootProvider.cs
Labels: area-NativeAOT

#643 Strip "likely unreachable" instance method bodies
  src/coreclr/nativeaot/System.Private.CoreLib/src/Internal/Runtime/CompilerHelpers/ThrowHelpers.cs
  src/coreclr/nativeaot/System.Private.CoreLib/src/Resources/Strings.resx
  src/coreclr/tools/Common/TypeSystem/Interop/IL/PInvokeDelegateWrapper.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Compilation.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/CompilationBuilder.Aot.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/CompilationModuleGroup.Aot.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ILScanNodeFactory.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_ARM/ARMTentativeInstanceMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_ARM64/ARM64TentativeInstanceMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_X64/X64TentativeInstanceMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_X86/X86TentativeInstanceMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/TentativeInstanceMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/IInliningPolicy.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/MethodExtensions.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/MultiFileCompilationModuleGroup.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/SingleFileCompilationModuleGroup.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/SingleMethodCompilationModuleGroup.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/ILCompiler.Compiler.csproj
  src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/DependencyAnalysis/RyuJitNodeFactory.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilationBuilder.cs
  src/coreclr/tools/aot/ILCompiler/Program.cs
Labels: area-NativeAOT

#652 Dataflow-annotate more APIs
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Enum.CoreRT.cs
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.CoreRT.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/NonOverriddenApis.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/ThunkedApis.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/Modules/RuntimeModule.cs
  src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs
  src/libraries/System.Private.CoreLib/src/System/Type.cs
Labels: area-NativeAOT

#663 ObjWriter fixes for Windows ARM64
  src/coreclr/tools/aot/ObjWriter/llvm.patch
  src/coreclr/tools/aot/ObjWriter/objwriter.cpp
Labels: area-NativeAOT

#658 Optimize away unused virtual implementations on abstract classes
  src/coreclr/nativeaot/System.Private.CoreLib/src/Internal/Runtime/CompilerHelpers/ThrowHelpers.cs
  src/coreclr/nativeaot/System.Private.CoreLib/src/Resources/Strings.resx
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/CompilationModuleGroup.Aot.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/EETypeNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_ARM/ARMTentativeMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_ARM64/ARM64TentativeMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_X64/X64TentativeMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/Target_X86/X86TentativeMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/TentativeInstanceMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/TentativeMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/FeatureSwitchManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/MultiFileCompilationModuleGroup.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/SingleFileCompilationModuleGroup.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/SingleMethodCompilationModuleGroup.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/ILCompiler.Compiler.csproj
  src/tests/nativeaot/SmokeTests/DeadCodeElimination/DeadCodeElimination.cs
  src/tests/nativeaot/SmokeTests/DeadCodeElimination/DeadCodeElimination.csproj
Labels: area-NativeAOT

#671 Generate debug info for all types that can be allocated
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/GCStaticsNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ISymbolNodeWithDebugInfo.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NonGCStaticsNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/ILCompiler.Compiler.csproj
Labels: area-NativeAOT

#650 s390x fixes that enable 100% test suite pass - Part 1
  src/mono/mono/arch/s390x/s390x-codegen.h
  src/mono/mono/mini/cpu-s390x.md
  src/mono/mono/mini/exceptions-s390x.c
  src/mono/mono/mini/mini-s390x.c
  src/mono/mono/mini/mini-s390x.h
  src/mono/mono/mini/tramp-s390x.c
  src/mono/mono/utils/mono-context.h
  src/mono/mono/utils/mono-sigcontext.h
  src/mono/netcore/System.Private.CoreLib/src/System/Array.Mono.cs
Labels: area-s390x

#580 s390x: Fix testhost creation
  eng/Subsets.props
  src/libraries/externals.csproj
Labels: area-s390x

#677 Make ThrowInstanceBodyRemoved/ThrowBodyRemoved helpers optional
  src/coreclr/tools/Common/TypeSystem/IL/HelperExtensions.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/TentativeInstanceMethodNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/TentativeMethodNode.cs
Labels: area-NativeAOT

#665 Revert "Use helix staging environment"
  eng/pipelines/libraries/helix.yml
Labels: area-s390x

#678 Annotate a couple more marshal APIs
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.CoreRT.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs
  src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs
Labels: area-NativeAOT

#681 Make Enum.GetValues<TEnum> guaranteed to work
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Enum.CoreRT.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/ThunkedApis.cs
  src/libraries/System.Private.CoreLib/src/System/Enum.cs
  src/libraries/System.Private.CoreLib/src/System/Type.cs
Labels: area-NativeAOT

#684 Make DataContractSerializer work
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets
  src/libraries/System.Private.DataContractSerialization/src/ILLink/ILLink.Substitutions.xml
  src/libraries/System.Private.DataContractSerialization/src/System.Private.DataContractSerialization.csproj
  src/tests/issues.targets
Labels: area-NativeAOT

#685 Early out in VEH for debugger exceptions
  src/coreclr/nativeaot/Runtime/EHHelpers.cpp
  src/coreclr/nativeaot/Runtime/PalRedhawk.h
Labels: area-NativeAOT

#683 Emit message for RequiresXYZCodeAttribute
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/DiagnosticUtilities.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs
Labels: area-NativeAOT

#687 Faster ObjWriter builds
  src/coreclr/inc/cfi.h
  src/coreclr/tools/aot/ObjWriter/CMakeLists.txt
  src/coreclr/tools/aot/ObjWriter/build.cmd
  src/coreclr/tools/aot/ObjWriter/build.sh
  src/coreclr/tools/aot/ObjWriter/cfi.h
  src/coreclr/tools/aot/ObjWriter/cordebuginfo.h
  src/coreclr/tools/aot/ObjWriter/cvconst.h
  src/coreclr/tools/aot/ObjWriter/objwriter.def
Labels: area-NativeAOT

#689 Fix emitting CodeView information for locals
  src/coreclr/inc/cvconst.h
  src/coreclr/tools/aot/ObjWriter/jitDebugInfo.h
  src/coreclr/tools/aot/ObjWriter/objwriter.cpp
  src/coreclr/tools/aot/ObjWriter/objwriter.h
Labels: area-NativeAOT

#693 Speed up reflection invoke
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/Internal/Reflection/Core/Execution/MethodInvoker.cs
Labels: area-NativeAOT

#696 Enable building of apphost and targeting packs tarballs
  src/installer/pkg/sfx/Microsoft.NETCore.App/Directory.Build.targets
Labels: area-s390x

#697 Delete __ComObject
  src/coreclr/nativeaot/Directory.Build.props
  src/coreclr/nativeaot/System.Private.CoreLib/src/Internal/Reflection/Augments/ReflectionAugments.cs
  src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.CoreRT.cs
  src/coreclr/nativeaot/System.Private.DisabledReflection/src/Internal/Reflection/ReflectionCoreCallbacksImplementation.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System.Private.Reflection.Core.csproj
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/Dispensers.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/ReflectionCoreCallbacksImplementation.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/TypeUnifier.cs
  src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/TypeInfos/RuntimeClsIdTypeInfo.cs
Labels: area-NativeAOT

#695 Use function pointers instead of a delegate in Marshal
  src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.CoreRT.cs
Labels: area-NativeAOT

#694 Delete RhpCheckCctor
  src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/InternalCalls.cs
  src/coreclr/nativeaot/Runtime/AsmOffsets.h
  src/coreclr/nativeaot/Runtime/ICodeManager.h
  src/coreclr/nativeaot/Runtime/MiscHelpers.cpp
  src/coreclr/nativeaot/Runtime/amd64/MiscStubs.asm
  src/coreclr/nativeaot/Runtime/arm/MiscStubs.asm
  src/coreclr/nativeaot/Runtime/arm64/MiscStubs.S
  src/coreclr/nativeaot/Runtime/arm64/MiscStubs.asm
  src/coreclr/nativeaot/Runtime/i386/MiscStubs.asm
  src/coreclr/nativeaot/Runtime/inc/rhbinder.h
Labels: area-NativeAOT

#692 Make DataContractSerializer more AOT friendly
  src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/AccessorBuilder.cs
Labels: area-NativeAOT

#690 Silence some marshalling warnings
  src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs
  src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs
Labels: area-NativeAOT

#701 Append dot to warning messages conditionally
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs
Labels: area-NativeAOT

#703 Refresh code shared with IL Linker
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReferenceSource/README.md
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReferenceSource/ReflectionMethodBodyScanner.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs
Labels: area-NativeAOT

#706 Build the PDB for ObjWriter
  src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj
  src/coreclr/tools/aot/ObjWriter/build.cmd
Labels: area-NativeAOT

#723 ObjWriter fixes
  src/coreclr/tools/aot/ObjWriter/debugInfo/dwarf/dwarfTypeBuilder.cpp
  src/coreclr/tools/aot/ObjWriter/objwriter.cpp
Labels: area-NativeAOT

#724 Fix CodeView register mapping on AMD64
  src/coreclr/tools/aot/ObjWriter/objwriter.cpp
Labels: area-NativeAOT

#725 Fix debug build of ObjWriter
  src/coreclr/tools/aot/ObjWriter/llvm.patch
Labels: area-NativeAOT

#730 Hide symbols instead of making them local
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs
  src/coreclr/tools/aot/ObjWriter/objwriter.cpp
Labels: area-NativeAOT

#729 Cleanup any leftover native artifacts from tests
  src/tests/Common/CLRTest.NativeAot.targets
Labels: area-NativeAOT

#731 Fix building packages
  Directory.Build.props
  src/installer/pkg/projects/Microsoft.DotNet.ILCompiler/Microsoft.DotNet.ILCompiler.pkgproj
Labels: area-NativeAOT

#732 Bump ObjWriter
  src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj
Labels: area-NativeAOT

#734 Support nested types
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.Tests/JsonSourceGeneratorTests.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.UnitTests/JsonSourceGeneratorDiagnosticsTests.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration.UnitTests/JsonSourceGeneratorTests.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/JsonSourceGenerator.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/JsonSourceGeneratorHelper.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/ReflectionUtils/TypeExtensions.cs
  src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/ReflectionUtils/TypeWrapper.cs
Labels: area-JsonCodeGen

#709 Add debug header for diagnostic tools
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets
  src/coreclr/nativeaot/Runtime/CMakeLists.txt
  src/coreclr/nativeaot/Runtime/DebugHeader.cpp
  src/coreclr/nativeaot/Runtime/RuntimeInstance.h
  src/coreclr/nativeaot/Runtime/inc/eetype.h
  src/coreclr/nativeaot/Runtime/inc/stressLog.h
  src/coreclr/nativeaot/Runtime/startup.cpp
  src/coreclr/nativeaot/Runtime/threadstore.h
Labels: area-NativeAOT

#735 Add information about state machine MoveNext methods
  src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs
  src/coreclr/tools/Common/TypeSystem/Ecma/SymbolReader/PdbSymbolReader.cs
  src/coreclr/tools/Common/TypeSystem/Ecma/SymbolReader/PortablePdbSymbolReader.cs
  src/coreclr/tools/Common/TypeSystem/Ecma/SymbolReader/UnmanagedPdbSymbolReader.cs
  src/coreclr/tools/Common/TypeSystem/IL/EcmaMethodIL.Symbols.cs
  src/coreclr/tools/Common/TypeSystem/IL/MethodIL.Symbols.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/INodeWithDebugInfo.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunHelperNode.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/DependencyAnalysis/MethodCodeNode.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs
Labels: area-NativeAOT

#740 Allow StartupCodeHelpers to be missing
  src/coreclr/tools/aot/ILCompiler.Compiler/IL/Stubs/StartupCode/StartupCodeMainMethod.cs
Labels: area-NativeAOT

#744 Speed up debug var info generation
  src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs
  src/coreclr/tools/Common/TypeSystem/IL/MethodIL.Symbols.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/INodeWithDebugInfo.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunHelperNode.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/DependencyAnalysis/MethodCodeNode.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs
Labels: area-NativeAOT

#746 Print more useful information on GVM resolution failure
  src/coreclr/nativeaot/System.Private.CoreLib/src/Internal/Runtime/CompilerServices/GenericVirtualMethodSupport.cs
Labels: area-NativeAOT

#750 Disable tiered compilation of ILCompiler
  src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj
Labels: area-NativeAOT

#752 Refresh files shared with IL Linker
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReferenceSource/README.md
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReferenceSource/ReflectionMethodBodyScanner.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs
Labels: area-NativeAOT
