Repository dotnet/runtimelab, pull requests merged in 2024-12, with the labels that each got.

#2820 [SwiftBindings] Add Type Database documentation
  src/docs/binding-typedatabase.md
Labels: area-SwiftBindings

#2813 [SwiftBindings] Added support for size, stride, alignment, and the value witness table
  src/Swift.Runtime/src/Metadata/TypeMetadata.cs
  src/Swift.Runtime/src/Metadata/ValueWitnessTable.cs
Labels: area-SwiftBindings

#2821 [SwiftBindings] Type database typos
  src/docs/binding-typedatabase.md
Labels: area-SwiftBindings

#2848 [NativeAOT-LLVM] Add an option to select the LLVM checkout path
  eng/pipelines/runtimelab/install-llvm.ps1
Labels: area-NativeAOT-LLVM

#2847 [RuntimeAsync] Fix support for pinvokes
  src/coreclr/jit/async.cpp
  src/coreclr/jit/compiler.cpp
  src/coreclr/jit/lower.cpp
  src/tests/async/pinvoke.cs
  src/tests/async/pinvoke.csproj
Labels: area-async

#2854 [RuntimeAsync] Fix a couple of cases where x86 would overwrite ecx on return
  src/coreclr/jit/codegenxarch.cpp
Labels: area-async

#2811 [SwiftBindings] Describe protocol constraints
  src/docs/binding-generics.md
Labels: area-SwiftBindings

#2780 Status and incomplete fat `Precode` pointer.
  experiment_status.md
  src/coreclr/vm/amd64/CallDescrWorkerAMD64.asm
  src/coreclr/vm/amd64/asmconstants.h
  src/coreclr/vm/callhelpers.cpp
  src/coreclr/vm/callhelpers.h
  src/coreclr/vm/interpreter.cpp
  src/coreclr/vm/interpreter.h
  src/coreclr/vm/jitinterface.cpp
  src/coreclr/vm/method.cpp
  src/coreclr/vm/precode.cpp
  src/coreclr/vm/precode.h
  src/coreclr/vm/reflectioninvocation.cpp
Labels: area-CoreclrInterpreter

#2862 [SwiftBindings] Formatting, typos, renamed SwiftHandle
  src/docs/README.md
  src/docs/binding-classes.md
  src/docs/binding-closures.md
  src/docs/binding-enums.md
  src/docs/binding-functions.md
  src/docs/binding-generics.md
  src/docs/binding-overview.md
  src/docs/binding-pats.md
  src/docs/binding-process-overview.md
  src/docs/binding-protocols.md
  src/docs/binding-structs.md
  src/docs/binding-tuples.md
  src/docs/binding-typedatabase.md
  src/docs/binding-value-witness-table.md
  src/docs/binding-variables.md
  src/docs/demangling.md
  src/docs/process-binding.md
  src/docs/runtime-existential-containers.md
  src/docs/runtime-metadata.md
  src/docs/runtime-nominal-type-descriptor.md
  src/docs/vtable-alternative.md
Labels: area-SwiftBindings

#2864 [NativeAOT-LLVM] Rename FEATURE_WASM_THREADS to FEATURE_WASM_MANAGED_THREADS
  src/coreclr/gc/gcpriv.h
  src/coreclr/nativeaot/Runtime/GCHelpers.cpp
  src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp
  src/coreclr/nativeaot/Runtime/wasm/AllocFast.cpp
  src/coreclr/nativeaot/Runtime/wasm/PalRedhawkWasm.cpp
  src/coreclr/nativeaot/Runtime/wasm/PalRedhawkWasm.h
Labels: area-NativeAOT-LLVM

#2818 [RuntimeAsync] Switch the implementation to the new shape of runtime async methods.
  buildroslynnugets.cmd
  eng/Versions.props
  src/coreclr/inc/corcompile.h
  src/coreclr/inc/corhdr.h
  src/coreclr/vm/class.cpp
  src/coreclr/vm/clrtocomcall.cpp
  src/coreclr/vm/clsload.cpp
  src/coreclr/vm/codeman.cpp
  src/coreclr/vm/commodule.cpp
  src/coreclr/vm/commtmemberinfomap.cpp
  src/coreclr/vm/comtoclrcall.cpp
  src/coreclr/vm/dispatchinfo.cpp
  src/coreclr/vm/dllimport.cpp
  src/coreclr/vm/encee.cpp
  src/coreclr/vm/genericdict.cpp
  src/coreclr/vm/genmeth.cpp
  src/coreclr/vm/instmethhash.cpp
  src/coreclr/vm/instmethhash.h
  src/coreclr/vm/interoputil.cpp
  src/coreclr/vm/jitinterface.cpp
  src/coreclr/vm/method.cpp
  src/coreclr/vm/method.hpp
  src/coreclr/vm/methoditer.cpp
  src/coreclr/vm/methodtable.cpp
  src/coreclr/vm/methodtablebuilder.cpp
  src/coreclr/vm/methodtablebuilder.h
  src/coreclr/vm/multicorejit.cpp
  src/coreclr/vm/prestub.cpp
  src/coreclr/vm/readytoruninfo.cpp
  src/coreclr/vm/zapsig.cpp
  src/libraries/System.Formats.Nrbf/src/System/Formats/Nrbf/ArraySinglePrimitiveRecord.cs
  src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs
  src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.MetadataDb.cs
  src/tests/async/pgo.cs
  src/tests/async/pgo.csproj
Labels: area-async

#2879 [Swift bindings] Upgrade dotnet runtime version to 9.0.0
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/core-templates/job/source-build.yml
  eng/common/core-templates/steps/source-build.yml
  eng/common/native/install-dependencies.sh
  eng/common/sdk-task.ps1
  eng/common/tools.ps1
  eng/common/tools.sh
  global.json
Labels: area-SwiftBindings

#2880 [Swift bindings] Make projection tooling AOT compatible
  src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/ModuleHandler.cs
  src/Swift.Bindings/src/Marshaler/Conductor.cs
  src/Swift.Bindings/src/Swift.Bindings.csproj
  src/Swift.Runtime/src/Swift.Runtime.csproj
  src/Swift.Runtime/src/TypeDatabase.cs
  src/Swift.Runtime/src/TypeDatabase.xml
  src/Swift.Runtime/src/Util/DynamicLibraryLoader.cs
Labels: area-SwiftBindings

#2894 [RuntimeAsync] Delete CODEOWNERS to avoid notifications
  .github/CODEOWNERS
Labels: area-async

#2893 [SwiftBindings] Extra enum-specific entries in ValueWitnessTable
  src/Swift.Runtime/src/Metadata/ValueWitnessTable.cs
Labels: area-SwiftBindings

#2870 [SwiftBindings] Add support for non-frozen structs
  .gitignore
  src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/MethodHandler.cs
  src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/ModuleHandler.cs
  src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/TypeHandler.cs
  src/Swift.Bindings/src/Emitter/StringCSharpEmitter/ModuleEmitter.cs
  src/Swift.Bindings/src/Marshaler/Conductor.cs
  src/Swift.Bindings/src/Marshaler/IEnvironment.cs
  src/Swift.Bindings/src/Marshaler/IHandler.cs
  src/Swift.Bindings/src/Marshaler/MarshallingHelpers.cs
  src/Swift.Bindings/src/Model/StructDecl.cs
  src/Swift.Bindings/src/Parser/SwiftABIParser.cs
  src/Swift.Bindings/tests/IntegrationTests/StressTests/NonFrozenStructs/NonFrozenStructsTests.cs
  src/Swift.Bindings/tests/IntegrationTests/StressTests/NonFrozenStructs/NonFrozenStructsTests.swift
  src/Swift.Runtime/src/TypeDatabase.cs
  src/Swift.Runtime/src/TypeDatabase.xml
  src/Swift.Runtime/src/TypeRegistrar.cs
Labels: area-SwiftBindings

#2859 [NativeAOT-LLVM] Add the `WasmComponentTypeWit` item group
  docs/using-nativeaot/compiling.md
  src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets
  src/tests/nativeaot/SmokeTests/SharedLibrary/SharedLibrary.cs
  src/tests/nativeaot/SmokeTests/SharedLibrary/SharedLibrary.csproj
Labels: area-NativeAOT-LLVM

#2878 [Swift bindings] Add bindings experimental NuGet to the dotnet-experimental feed
  .gitignore
  SwiftBindings.sln
  dotnet.sh
  eng/pipelines/common/templates/build-job.yml
  eng/pipelines/runtimelab-official.yml
  generate.sh
  src/Swift.Bindings/src/Program.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/.gitignore
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/AppDelegate.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon1024.png
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon128.png
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon16.png
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon256.png
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon32.png
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon512.png
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon64.png
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/TrailImage.imageset/Contents.json
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/TrailImage.imageset/TrailImage.svg
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Directory.Build.props
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Entitlements.plist
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/HikingApp.MacCatalyst.csproj
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/HikingApp.MacCatalyst.sln
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Info.plist
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Main.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Models/Trail.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/README.md
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/Resources/LaunchScreen.xib
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/SceneDelegate.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/ViewControllers/ExploreViewController.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/ViewControllers/LoginViewController.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/ViewControllers/MainViewController.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/ViewControllers/MyTrailsViewController.cs
  src/Swift.Bindings/tests/FrameworkTests/HikingApp/HikingApp.MacCatalyst/ViewControllers/TrailViewController.cs
  src/Swift.Bindings/tests/FrameworkTests/Swift.Bindings.Framework.Tests.csproj
  src/Swift.Bindings/tests/IntegrationTests/CMakeLists.txt
  src/Swift.Bindings/tests/IntegrationTests/Swift.Bindings.Integration.Tests.csproj
  src/Swift.Bindings/tests/TestsHelper.cs
  src/Swift.Runtime/src/ManualBindings/ISwiftObject.cs
  src/Swift.Runtime/src/ManualBindings/KnownLibraries.cs
  src/Swift.Runtime/src/ManualBindings/SwiftHandle.cs
  src/Swift.Runtime/src/ManualBindings/UnsafeBufferPointer.cs
  src/Swift.Runtime/src/ManualBindings/UnsafePointer.cs
  src/Swift.Runtime/src/Metadata/Arc.cs
  src/Swift.Runtime/src/Swift.Runtime.csproj
Labels: area-SwiftBindings

#2901 [SwiftBindings] Initialize functional tests for structs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/CryptoKit/CryptoKit.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/CryptoKit/CryptoKitTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/CryptoKit/Foundation.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Structs/StructsTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Structs/StructsTests.swift
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/UnsafeBufferPointer/UnsafeBufferPointerTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/UnsafePointer/UnsafePointerTests.cs
  src/Swift.Bindings/tests/IntegrationTests/StressTests/FrozenStructs/FrozenStructsTests.cs
  src/Swift.Bindings/tests/IntegrationTests/StressTests/NonFrozenStructs/NonFrozenStructsTests.cs
  src/Swift.Bindings/tests/IntegrationTests/StressTests/PInvoke/PInvokeTests.cs
  src/Swift.Bindings/tests/IntegrationTests/StressTests/StaticMethods/StaticMethodsTests.cs
Labels: area-SwiftBindings

#2899 [NativeAOT-LLVM] Disable `SharedLibrary.csproj`
  eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
  src/tests/Common/dirs.proj
Labels: area-NativeAOT-LLVM

#2883 [NativeAOT-LLVM] Emit type debug info into a single module
  eng/pipelines/runtimelab/install-wasmtime.ps1
  src/coreclr/jit/llvm.cpp
  src/coreclr/jit/llvm.h
  src/coreclr/jit/llvmdebuginfo.cpp
  src/coreclr/tools/Common/Internal/Text/Utf8String.cs
  src/coreclr/tools/Common/JitInterface/JitEEApi.Shared.cspp
  src/coreclr/tools/Common/TypeSystem/TypesDebugInfoWriter/TypesDebugInfoWriter.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/MetadataManager.cs
  src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs
  src/coreclr/tools/aot/ILCompiler.LLVM/Compiler/DependencyAnalysis/LLVMMethodCodeNode.cs
  src/coreclr/tools/aot/ILCompiler.LLVM/Compiler/LLVMCodegenCompilation.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.Llvm.DebugInfo.cs
  src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.Llvm.cs
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebugging.cs
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebugging.py
Labels: area-NativeAOT-LLVM
