Repository dotnet/runtimelab, pull requests merged in 2024-11, with the labels that each got.

#2754 [Swift-bindings] Remove HikingApp from the main project solution
  SwiftBindings.sln
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
  src/samples/HikingApp/HikingApp.MacCatalyst/HikingApp.MacCatalyst.sln
  src/samples/HikingApp/HikingApp.MacCatalyst/README.md
Labels: area-SwiftBindings

#2757 [SwiftBindings] Better demangle errors
  src/Swift.Bindings/src/Demangler/Enums.cs
  src/Swift.Bindings/src/Demangler/IReduction.cs
  src/Swift.Bindings/src/Demangler/Swift5Reducer.cs
  src/Swift.Bindings/tests/DemanglerTests/BasicDemanglingTests.cs
Labels: area-SwiftBindings

#2777 [NativeAOT-LLVM] update Wasmtime version
  eng/pipelines/runtimelab/install-wasmtime.ps1
Labels: area-NativeAOT-LLVM

#2776 [NativeAOT-LLVM] ignore `-Wdeprecated-declarations` in llvmlssa.cpp
  src/coreclr/jit/llvmlssa.cpp
Labels: area-NativeAOT-LLVM

#2775 [NativeAOT-LLVM] only require EMSDK when building for browser
  src/coreclr/build-runtime.cmd
Labels: area-NativeAOT-LLVM

#2761 [SwiftBindings] added full demangling results with easy accessors and cleaned up the code to require fewer allocations
  src/Swift.Bindings/src/Demangler/DemanglingResults.cs
  src/Swift.Bindings/src/Demangler/Swift5Demangler.cs
  src/Swift.Bindings/src/Demangler/Swift5Reducer.cs
  src/Swift.Bindings/src/Model/SwiftFunction.cs
  src/Swift.Bindings/tests/DemanglerTests/BasicDemanglingTests.cs
  src/Swift.Bindings/tests/MachOTests/MachOTests.cs
Labels: area-SwiftBindings

#2782 [NativeAOT-LLVM] `UseAppHost: false` for the HelloWorld sample
  samples/HelloWorld/HelloWorld.csproj
Labels: area-NativeAOT-LLVM

#2778 [NativeAOT-LLVM] update `SharedLibrary` smoke test for WASIp2
  eng/pipelines/common/global-build-job.yml
  eng/pipelines/runtimelab/install-jco.ps1
  eng/pipelines/runtimelab/install-nodejs.ps1
  src/tests/nativeaot/SmokeTests/SharedLibrary/.npmrc
  src/tests/nativeaot/SmokeTests/SharedLibrary/SharedLibrary.cs
  src/tests/nativeaot/SmokeTests/SharedLibrary/SharedLibrary.csproj
  src/tests/nativeaot/SmokeTests/SharedLibrary/SharedLibraryDriver.mjs
  src/tests/nativeaot/SmokeTests/SharedLibrary/package-lock.json
  src/tests/nativeaot/SmokeTests/SharedLibrary/package.json
  src/tests/nativeaot/SmokeTests/SharedLibrary/wit/world.wit
Labels: area-NativeAOT-LLVM

#2781 awaits of Task-returning methods from async2 are done as thunk calls.
  buildroslynnugets.cmd
  eng/Versions.props
  src/coreclr/vm/corelib.h
  src/coreclr/vm/method.hpp
  src/coreclr/vm/prestub.cpp
Labels: area-async

#2792 Exclude src/docs from CI
  eng/pipelines/runtimelab-official.yml
  eng/pipelines/runtimelab.yml
Labels: area-SwiftBindings

#2791 [NativeAOT-LLVM] Use `DebugType=none` instead of `NativeDebugSymbols=false`
  docs/using-nativeaot/compiling.md
Labels: area-NativeAOT-LLVM

#2771 [SwiftBindings] Document generic methods
  src/docs/binding-generics.md
Labels: area-SwiftBindings

#2785 [NativeAOT-LLVM] Automate `WasmDebugging.csproj` via LLDB scripting
  eng/pipelines/common/global-build-job.yml
  eng/pipelines/common/platform-matrix.yml
  eng/pipelines/common/templates/pipeline-with-resources.yml
  eng/pipelines/runtimelab/install-build-and-test-tools.sh
  eng/pipelines/runtimelab/install-lldb.sh
  eng/pipelines/runtimelab/install-python.sh
  eng/pipelines/runtimelab/install-wasmtime.ps1
  eng/testing/FindWasmHostExecutable.sh
  src/tests/Common/CLRTest.Execute.Batch.targets
  src/tests/Common/dirs.proj
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebugging.csproj
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebugging.py
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebuggingTestLauncher.cmd
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebuggingTestLauncher.sh
Labels: area-NativeAOT-LLVM

#2779 [SwiftBindings] Binding process doc
  src/docs/process-binding.md
Labels: area-SwiftBindings

#2796 [SwiftBindings] Describe projecting generic structs
  src/docs/binding-generics.md
Labels: area-SwiftBindings

#2809 [SwiftBindings] Added missing types and renamed Protocol->Existential
  src/Swift.Runtime/src/Metadata/TypeMetadata.cs
Labels: area-SwiftBindings

#2812 [RuntimeAsync] Keep `LoaderAllocator` objects alive from continuations
  src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs
  src/coreclr/inc/corinfo.h
  src/coreclr/inc/jithelpers.h
  src/coreclr/jit/async.cpp
  src/coreclr/jit/async.h
  src/coreclr/jit/compiler.h
  src/coreclr/jit/compiler.hpp
  src/coreclr/tools/superpmi/superpmi-shared/agnostic.h
  src/coreclr/tools/superpmi/superpmi-shared/methodcontext.cpp
  src/coreclr/vm/appdomain.cpp
  src/coreclr/vm/comutilnative.cpp
  src/coreclr/vm/comutilnative.h
  src/coreclr/vm/corelib.h
  src/coreclr/vm/ecall.cpp
  src/coreclr/vm/ecall.h
  src/coreclr/vm/ecalllist.h
  src/coreclr/vm/jitinterface.cpp
  src/tests/async/collectible-alc.cs
  src/tests/async/collectible-alc.csproj
  src/tests/issues.targets
Labels: area-async

#2774 Interpreter design docs
  docs/design/interpreter/compiled-code-interop.md
  docs/design/interpreter/precise-gc.md
Labels: area-CoreclrInterpreter
