Repository dotnet/runtimelab, pull requests merged in 2024-10, with the labels that each got.

#2694 [Swift Bindings] Added demangling support for protocol conformance descriptors and nested type names
  src/Swift.Bindings/src/Demangler/IReduction.cs
  src/Swift.Bindings/src/Demangler/MatchRule.cs
  src/Swift.Bindings/src/Demangler/Swift5Reducer.cs
  src/Swift.Bindings/tests/DemanglerTests/BasicDemanglingTests.cs
Labels: area-SwiftBindings

#2704 Add experimental Swift bindings for CryptoKit
  eng/Versions.props
  global.json
  src/Swift.Bindings/tests/CryptoKit/CryptoKit.Source.cs
  src/Swift.Bindings/tests/CryptoKit/CryptoKitTests.Source.cs
  src/Swift.Bindings/tests/CryptoKit/CryptoKitTests.cs
  src/Swift.Bindings/tests/CryptoKit/Foundation.Source.cs
  src/Swift.Bindings/tests/TestsHelper.cs
Labels: area-SwiftBindings

#2698 Interpreter Fixes (#108485)
  eng/pipelines/runtimelab-official.yml
  eng/pipelines/runtimelab.yml
  src/coreclr/vm/interpreter.cpp
  src/coreclr/vm/interpreter.h
  src/coreclr/vm/stublink.cpp
Labels: area-CoreclrInterpreter

#2716 Add tracking markdown.
  generated_codegen.md
Labels: area-CoreclrInterpreter

#2707 [SwiftBindings] Documented binding PATs and alternative to vtables
  src/docs/binding-classes.md
  src/docs/binding-pats.md
  src/docs/binding-protocols.md
  src/docs/vtable-alternative.md
Labels: area-SwiftBindings

#2715 Update SystemTextJsonToolsetVersion (#108704)
  eng/Versions.props
  eng/pipelines/runtimelab.yml
  src/coreclr/inc/stack.h
  src/coreclr/vm/interpreter.cpp
  src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.External.Tests/Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj
  src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj
Labels: area-CoreclrInterpreter

#2721 Fix `Delegate` dispatch.
  src/coreclr/vm/comdelegate.cpp
  src/coreclr/vm/interpreter.cpp
  src/coreclr/vm/interpreter.h
  src/coreclr/vm/stublink.cpp
Labels: area-CoreclrInterpreter

#2725 Disable PerfTracing
  src/coreclr/clr.featuredefines.props
  src/coreclr/vm/interpreter.cpp
  src/coreclr/vm/jitinterface.cpp
Labels: area-CoreclrInterpreter

#2719 Audit all uses of ExecutableWriterHolder and ExecutableWriterHolderNo…
  generated_codegen.md
Labels: area-CoreclrInterpreter

#2726 HikingApp Mac Catalyst sample app
  NuGet.config
  SwiftBindings.sln
  eng/restore-toolset.sh
  src/samples/HikingApp/HikingApp.MacCatalyst/.gitignore
  src/samples/HikingApp/HikingApp.MacCatalyst/AppDelegate.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon1024.png
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon128.png
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon16.png
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon256.png
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon32.png
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon512.png
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/AppIcon.appiconset/Icon64.png
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/TrailImage.imageset/Contents.json
  src/samples/HikingApp/HikingApp.MacCatalyst/Assets.xcassets/TrailImage.imageset/TrailImage.svg
  src/samples/HikingApp/HikingApp.MacCatalyst/Directory.Build.props
  src/samples/HikingApp/HikingApp.MacCatalyst/Entitlements.plist
  src/samples/HikingApp/HikingApp.MacCatalyst/HikingApp.MacCatalyst.csproj
  src/samples/HikingApp/HikingApp.MacCatalyst/Info.plist
  src/samples/HikingApp/HikingApp.MacCatalyst/Main.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/Models/Trail.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/README.md
  src/samples/HikingApp/HikingApp.MacCatalyst/Resources/LaunchScreen.xib
  src/samples/HikingApp/HikingApp.MacCatalyst/SceneDelegate.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/ViewControllers/ExploreViewController.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/ViewControllers/LoginViewController.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/ViewControllers/MainViewController.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/ViewControllers/MyTrailsViewController.cs
  src/samples/HikingApp/HikingApp.MacCatalyst/ViewControllers/TrailViewController.cs
Labels: area-SwiftBindings

#2732 Add `restore-toolset` script for publishing pipeline
  eng/restore-toolset.ps1
Labels: area-SwiftBindings

#2733 Pin Mac Catalyst workload version to 17.5.9270-net9-rc1
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
Labels: area-SwiftBindings

#2737 fix samples/NativeLibrary
  samples/HelloWorld/HelloWorld.csproj
  samples/NativeLibrary/NativeLibrary.csproj
Labels: area-NativeAOT-LLVM

#2741 Add demo IL application.
  App.il
  README.md
  generated_codegen.md
Labels: area-CoreclrInterpreter

#2740 Added support for finding metadata accessors
  src/Swift.Bindings/src/Demangler/IReduction.cs
  src/Swift.Bindings/src/Demangler/Swift5Reducer.cs
  src/Swift.Bindings/tests/DemanglerTests/BasicDemanglingTests.cs
Labels: area-SwiftBindings

#2742 [SwiftBinding] Create document structure
  src/docs/README.md
  src/docs/binding-overview.md
  src/docs/binding-process-overview.md
  src/docs/front-facing-interface.md
  src/docs/runtime-features-overview.md
Labels: area-SwiftBindings

#2724 documented swift closures
  src/docs/binding-closures.md
  src/docs/binding-overview.md
Labels: area-SwiftBindings

#2744 Allow build without sudo privileges
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
Labels: area-SwiftBindings
