Repository dotnet/runtimelab, pull requests merged in 2025-03, with the labels that each got.

#2988 [SwiftBindings] Document properties bindings
  src/docs/binding-properties.md
Labels: area-SwiftBindings

#3028 [Swift Bindings] Initialized static properties support
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/PropertyHandler.cs
  src/Swift.Bindings/src/Parser/SwiftABIParser.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Structs/StructsTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Structs/StructsTests.swift
  src/docs/binding-properties.md
Labels: area-SwiftBindings

#2857 Add documents on the Mono interpreter analysis
  docs/design/interpreter/debugger.md
  docs/design/interpreter/exception-handling.md
  docs/design/interpreter/execution.md
  docs/design/interpreter/experiment.md
  docs/design/interpreter/ir-byte-code.md
  docs/design/interpreter/stackwalk.md
  docs/design/interpreter/transformation.md
Labels: area-CoreclrInterpreter

#2872 Add documents on the CoreCLR without runtime code generation experiment
  interpreter_experiment.md
Labels: area-CoreclrInterpreter

#3032 [RuntimeAsync] Some VM cleanups, TODOs, renames and better comments.
  src/coreclr/debug/ee/functioninfo.cpp
  src/coreclr/inc/corcompile.h
  src/coreclr/vm/clrtocomcall.cpp
  src/coreclr/vm/clsload.cpp
  src/coreclr/vm/commodule.cpp
  src/coreclr/vm/commtmemberinfomap.cpp
  src/coreclr/vm/comtoclrcall.cpp
  src/coreclr/vm/dispatchinfo.cpp
  src/coreclr/vm/dllimport.cpp
  src/coreclr/vm/encee.cpp
  src/coreclr/vm/genericdict.cpp
  src/coreclr/vm/genmeth.cpp
  src/coreclr/vm/instmethhash.cpp
  src/coreclr/vm/instmethhash.h
  src/coreclr/vm/interoputil.cpp
  src/coreclr/vm/jitinterface.cpp
  src/coreclr/vm/method.cpp
  src/coreclr/vm/method.hpp
  src/coreclr/vm/methoditer.cpp
  src/coreclr/vm/methoditer.h
  src/coreclr/vm/methodtable.cpp
  src/coreclr/vm/methodtablebuilder.cpp
  src/coreclr/vm/methodtablebuilder.h
  src/coreclr/vm/multicorejit.cpp
  src/coreclr/vm/prestub.cpp
  src/coreclr/vm/readytoruninfo.cpp
  src/coreclr/vm/zapsig.cpp
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/MethodImplOptions.cs
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs
  src/libraries/System.Runtime/ref/System.Runtime.cs
Labels: area-async

#3042 [RuntimeAsync] Normalize the box type in resume stubs
  src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs
  src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs
  src/coreclr/vm/corelib.h
  src/coreclr/vm/jitinterface.cpp
  src/tests/async/shared-generic.cs
Labels: area-async

#3034 [swift] Use TBD files to retrieve symbols missing from abi.json
  generate.sh
  src/Swift.Bindings/src/DemangledSymbols.cs
  src/Swift.Bindings/src/Demangler/DemanglingResults.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Logging/ConsoleLogger.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Logging/ILogger.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Logging/NullLogger.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Models/ParsingException.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Models/Symbol.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Models/TbdFile.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Parsing/ITbdFormatParser.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Parsing/JsonTbdFormatParser.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Parsing/TbdFormatParserBase.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Parsing/YamlLikeTbdFormatParser.cs
  src/Swift.Bindings/src/Demangler/TbdParser/TbdParser.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/TypeHandler.cs
  src/Swift.Bindings/src/Model/TypeDecl/ModuleDecl.cs
  src/Swift.Bindings/src/Model/TypeDecl/ProtocolConformance.cs
  src/Swift.Bindings/src/Model/TypeDecl/StructDecl.cs
  src/Swift.Bindings/src/Parser/ModuleProcessor.cs
  src/Swift.Bindings/src/Parser/SwiftABIParser.cs
  src/Swift.Bindings/src/Program.cs
  src/Swift.Bindings/tests/IntegrationTests/CMakeLists.txt
  src/Swift.Bindings/tests/UnitTests/TbdParserTests/TbdParserTests.cs
  src/docs/demangling.md
  src/docs/retrieving-symbols-outside-abi-json.md
Labels: area-SwiftBindings

#3038 [Swift Bindings] Project value types with heap-allocated properties as C# classes
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/MethodHandler.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/TypeHandler.cs
  src/Swift.Bindings/src/Marshaler/BoundGenericsHandler.cs
  src/Swift.Bindings/src/Marshaler/MarshallingHelpers.cs
  src/Swift.Bindings/src/Model/TypeDecl/StructDecl.cs
  src/Swift.Bindings/src/Parser/ModuleProcessor.cs
  src/Swift.Bindings/src/Parser/SwiftABIParser.cs
  src/Swift.Bindings/src/TypeDatabase/TypeDatabase.cs
  src/Swift.Bindings/src/TypeDatabase/TypeDatabaseExtensions.cs
  src/Swift.Bindings/src/TypeDatabase/TypeRecord.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Async/AsyncTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/MemoryTests/MemoryTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/MemoryTests/MemoryTests.swift
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Runtime/RuntimeTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Runtime/RuntimeTests.swift
  src/Swift.Bindings/tests/UnitTests/TypeDatabaseTests/TypeDatabaseTests.cs
  src/Swift.Runtime/src/Swift/FoundationDatabase.xml
  src/Swift.Runtime/src/Swift/SwiftArray.cs
  src/Swift.Runtime/src/Swift/SwiftDatabase.xml
  src/Swift.Runtime/src/Swift/SwiftEquatable.cs
  src/Swift.Runtime/src/Swift/SwiftSet.cs
  src/Swift.Runtime/src/Swift/SwiftString.cs
  src/Swift.Runtime/tests/LibraryTests/SwiftArrayTests.cs
  src/Swift.Runtime/tests/LibraryTests/SwiftSetTests.cs
  src/Swift.Runtime/tests/LibraryTests/SwiftStringTests.cs
Labels: area-SwiftBindings

#3056 [Swift projection tooling] Remove MachO from the projection tooling
  src/Swift.Bindings/src/Demangler/DemanglingResults.cs
  src/Swift.Bindings/src/Demangler/MachO.cs
  src/Swift.Bindings/src/Demangler/MachOExtensions.cs
  src/Swift.Bindings/tests/UnitTests/MachOTests/MachOTests.cs
Labels: area-SwiftBindings

#3058 [Swift projection tooling] New logging mechanism using Microsoft.Extensions.Logging API
  src/Swift.Bindings/src/Demangler/DemanglingResults.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Logging/ConsoleLogger.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Logging/ILogger.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Logging/NullLogger.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Parsing/JsonTbdFormatParser.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Parsing/TbdFormatParserBase.cs
  src/Swift.Bindings/src/Demangler/TbdParser/Parsing/YamlLikeTbdFormatParser.cs
  src/Swift.Bindings/src/Demangler/TbdParser/TbdParser.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/HandlerFactory.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/MethodHandler.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/ModuleHandler.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/PropertyHandler.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/TypeHandler.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/ModuleEmitter.cs
  src/Swift.Bindings/src/Marshaler/Conductor.cs
  src/Swift.Bindings/src/Marshaler/IHandler.cs
  src/Swift.Bindings/src/Parser/ModuleProcessor.cs
  src/Swift.Bindings/src/Parser/SwiftABIParser.cs
  src/Swift.Bindings/src/Program.cs
  src/Swift.Bindings/src/Swift.Bindings.csproj
  src/Swift.Bindings/tests/UnitTests/TbdParserTests/TbdParserTests.cs
Labels: area-SwiftBindings
