Repository dotnet/runtimelab, pull requests merged in 2025-04, with the labels that each got.

#3069 [Swift bindings] Update `README.md` with new tooling console arguments
  README.md
  docs/README.md
  docs/binding-classes.md
  docs/binding-closures.md
  docs/binding-enums.md
  docs/binding-functions.md
  docs/binding-generics.md
  docs/binding-overview.md
  docs/binding-pats.md
  docs/binding-process-overview.md
  docs/binding-properties.md
  docs/binding-protocols.md
  docs/binding-structs.md
  docs/binding-tuples.md
  docs/binding-typedatabase.md
  docs/binding-value-witness-table.md
  docs/binding-variables.md
  docs/conductor-uml-outline.svg
  docs/demangling.md
  docs/front-facing-interface.md
  docs/functional-outline.svg
  docs/memory-management.md
  docs/process-binding.md
  docs/retrieving-symbols-outside-abi-json.md
  docs/runtime-existential-containers.md
  docs/runtime-features-overview.md
  docs/runtime-metadata.md
  docs/runtime-nominal-type-descriptor.md
  docs/swift-code-generation.md
  docs/vtable-alternative.md
  src/docs/README.md
Labels: area-SwiftBindings

#3052 [Swift Bindings] Implement Swift native handle as `SafeHandle`
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/MethodHandler.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/ModuleHandler.cs
  src/Swift.Bindings/src/Emitter/StringEmitter/Handler/TypeHandler.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Async/AsyncTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/CryptoKit/CryptoKit.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/CryptoKit/CryptoKitTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/MemoryTests/MemoryTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/MemoryTests/MemoryTests.swift
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Runtime/RuntimeTests.cs
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Runtime/RuntimeTests.swift
  src/Swift.Bindings/tests/IntegrationTests/FunctionalTests/Runtime/TestTypes.cs
  src/Swift.Bindings/tests/UnitTests/TbdParserTests/TbdParserTests.cs
  src/Swift.Runtime/src/Metadata/TypeMetadata.cs
  src/Swift.Runtime/src/Swift/AnyType.cs
  src/Swift.Runtime/src/Swift/Data.cs
  src/Swift.Runtime/src/Swift/Runtime/ISwiftObject.cs
  src/Swift.Runtime/src/Swift/Runtime/InteropServices/SwiftMarshal.cs
  src/Swift.Runtime/src/Swift/Runtime/SwiftHandle.cs
  src/Swift.Runtime/src/Swift/Runtime/TypeMetadata.cs
  src/Swift.Runtime/src/Swift/SwiftArray.cs
  src/Swift.Runtime/src/Swift/SwiftEquatable.cs
  src/Swift.Runtime/src/Swift/SwiftOptional.cs
  src/Swift.Runtime/src/Swift/SwiftSet.cs
  src/Swift.Runtime/src/Swift/SwiftString.cs
  src/Swift.Runtime/tests/LibraryTests/SwiftArrayTests.cs
  src/Swift.Runtime/tests/LibraryTests/SwiftOptionalTests.cs
  src/Swift.Runtime/tests/LibraryTests/SwiftSetTests.cs
  src/Swift.Runtime/tests/MetadataTests/ProtocolWitnessTableTests.cs
  src/Swift.Runtime/tests/MetadataTests/TestTypes.cs
  src/Swift.Runtime/tests/MetadataTests/TypeMetadataTests.cs
  src/samples/HelloWorld/build.sh
Labels: area-SwiftBindings

#3078 [RuntimeAsync] Porting fixes from the merge PR
  docs/design/features/runtime-handled-tasks.md
  src/coreclr/debug/ee/functioninfo.cpp
  src/coreclr/inc/eetwain.h
  src/coreclr/jit/codegenloongarch64.cpp
  src/coreclr/jit/codegenriscv64.cpp
  src/coreclr/jit/targetloongarch64.h
  src/coreclr/jit/targetriscv64.h
  src/coreclr/vm/arm/asmhelpers.S
  src/coreclr/vm/arm/cgencpu.h
  src/coreclr/vm/arm/stubs.cpp
  src/coreclr/vm/arm64/stubs.cpp
  src/coreclr/vm/commodule.cpp
  src/coreclr/vm/eetwain.cpp
  src/coreclr/vm/encee.cpp
  src/coreclr/vm/gcinfodecoder.cpp
  src/coreclr/vm/jitinterface.cpp
  src/coreclr/vm/methoditer.cpp
  src/coreclr/vm/methoditer.h
  src/coreclr/vm/methodtable.cpp
  src/coreclr/vm/methodtablebuilder.cpp
  src/coreclr/vm/methodtablebuilder.h
  src/coreclr/vm/runtimehandles.cpp
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/QCallHandles.cs
Labels: area-async

#3080 [RuntimeAsync] Remove new OSR transition helper
  src/coreclr/inc/corinfo.h
  src/coreclr/inc/jithelpers.h
  src/coreclr/jit/async.cpp
  src/coreclr/jit/patchpoint.cpp
  src/coreclr/tools/Common/JitInterface/CorInfoHelpFunc.cs
  src/coreclr/vm/amd64/AsmHelpers.asm
  src/coreclr/vm/amd64/unixasmhelpers.S
  src/coreclr/vm/arm64/asmhelpers.S
  src/coreclr/vm/arm64/asmhelpers.asm
  src/coreclr/vm/codeversion.cpp
  src/coreclr/vm/codeversion.h
  src/coreclr/vm/jithelpers.cpp
  src/coreclr/vm/jitinterface.h
  src/coreclr/vm/loongarch64/asmhelpers.S
  src/coreclr/vm/riscv64/asmhelpers.S
Labels: area-async

#3081 [RuntimeAync] Removing "async2" references
  src/coreclr/inc/corcompile.h
  src/coreclr/jit/gentree.cpp
  src/coreclr/vm/clrtocomcall.cpp
  src/coreclr/vm/clsload.cpp
  src/coreclr/vm/commodule.cpp
  src/coreclr/vm/commtmemberinfomap.cpp
  src/coreclr/vm/comtoclrcall.cpp
  src/coreclr/vm/dispatchinfo.cpp
  src/coreclr/vm/dllimport.cpp
  src/coreclr/vm/frames.cpp
  src/coreclr/vm/gcenv.ee.common.cpp
  src/coreclr/vm/genericdict.cpp
  src/coreclr/vm/genmeth.cpp
  src/coreclr/vm/instmethhash.cpp
  src/coreclr/vm/instmethhash.h
  src/coreclr/vm/interoputil.cpp
  src/coreclr/vm/jitinterface.cpp
  src/coreclr/vm/method.cpp
  src/coreclr/vm/method.hpp
  src/coreclr/vm/methodtable.cpp
  src/coreclr/vm/methodtablebuilder.cpp
  src/coreclr/vm/methodtablebuilder.h
  src/coreclr/vm/multicorejit.cpp
  src/coreclr/vm/prestub.cpp
  src/coreclr/vm/readytoruninfo.cpp
  src/coreclr/vm/runtimehandles.cpp
  src/coreclr/vm/siginfo.cpp
  src/coreclr/vm/threadsuspend.cpp
  src/coreclr/vm/zapsig.cpp
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs
Labels: area-async

#3084 [NativeAOT-LLVM] Fix saturating FP casts to small types
  src/coreclr/jit/llvmcodegen.cpp
  src/tests/Common/dirs.proj
Labels: area-NativeAOT-LLVM

#3082 [RuntimeAsync] Do not rely on signature parsing to figure if a call is Async
  src/coreclr/jit/importercalls.cpp
  src/coreclr/jit/namedintrinsiclist.h
  src/coreclr/vm/jitinterface.cpp
  src/coreclr/vm/method.hpp
  src/coreclr/vm/methodtablebuilder.cpp
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs
Labels: area-async

#3089 [RuntimeAsync] Mark continuation GC return for arm64/arm32/LA64/RISCV64
  src/coreclr/jit/emitarm.cpp
  src/coreclr/jit/emitarm64.cpp
  src/coreclr/jit/emitloongarch64.cpp
  src/coreclr/jit/emitriscv64.cpp
Labels: area-async

#3090 [RuntimeAsync] Model async continuation definition via delay-free
  src/coreclr/jit/lower.cpp
  src/coreclr/jit/lower.h
  src/coreclr/jit/lsra.cpp
  src/coreclr/jit/lsra.h
  src/coreclr/jit/lsraarm.cpp
  src/coreclr/jit/lsraarm64.cpp
  src/coreclr/jit/lsraarmarch.cpp
  src/coreclr/jit/lsrabuild.cpp
  src/coreclr/jit/lsraloongarch64.cpp
  src/coreclr/jit/lsrariscv64.cpp
  src/coreclr/jit/lsraxarch.cpp
Labels: area-async

#3092 [NativeAOT-LLVM] Switch back to released wasmtime
  eng/pipelines/runtimelab/install-wasmtime.ps1
Labels: area-NativeAOT-LLVM

#3094 [RuntimeAsync] Propagate profile weight flag for shared return BB on x86
  src/coreclr/jit/async.cpp
Labels: area-async

#3095 [RuntimeAsync] Feedback from the merging PR in the runtime repo.
  src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj
  src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs
  src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs
  src/coreclr/inc/jithelpers.h
  src/coreclr/jit/importercalls.cpp
  src/coreclr/jit/namedintrinsiclist.h
  src/coreclr/vm/CMakeLists.txt
  src/coreclr/vm/asyncthunks.cpp
  src/coreclr/vm/codeversion.cpp
  src/coreclr/vm/codeversion.h
  src/coreclr/vm/corelib.h
  src/coreclr/vm/jithelpers.cpp
  src/coreclr/vm/jitinterface.cpp
  src/coreclr/vm/method.cpp
  src/coreclr/vm/method.hpp
  src/coreclr/vm/prestub.cpp
  src/coreclr/vm/stubgen.cpp
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs
Labels: area-async

#3097 [RuntimeAsync] Replace async marker with a flag
  src/coreclr/jit/async.cpp
  src/coreclr/jit/fginline.cpp
  src/coreclr/jit/gentree.cpp
  src/coreclr/jit/gentree.h
  src/coreclr/jit/importercalls.cpp
  src/coreclr/jit/lower.cpp
  src/coreclr/jit/morph.cpp
Labels: area-async

#3098 [RuntimeAsync] Use the newest API
  buildroslynnugets.cmd
  eng/Versions.props
  src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs
  src/coreclr/jit/importer.cpp
  src/coreclr/jit/importercalls.cpp
  src/coreclr/jit/namedintrinsiclist.h
  src/coreclr/nativeaot/System.Private.CoreLib/src/CompatibilitySuppressions.xml
  src/coreclr/vm/asyncthunks.cpp
  src/coreclr/vm/corelib.h
  src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs
  src/libraries/System.Runtime/ref/System.Runtime.cs
  src/tests/async/fibonacci-without-yields-config-await.cs
Labels: area-async

#3099 [RuntimeAsync] Use approved value for MethodImplAttributes.Async
  buildroslynnugets.cmd
  eng/Versions.props
  src/coreclr/inc/corhdr.h
  src/libraries/System.Private.CoreLib/src/System/Reflection/MethodImplAttributes.cs
  src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/MethodImplOptions.cs
  src/libraries/System.Runtime/ref/System.Runtime.cs
Labels: area-async

#3059 [Swift Bindings] Emitter redesign proposal
  src/docs/emitter-redesign-proposal.md
Labels: area-SwiftBindings

#3100 [RuntimeAsync] Implement IL_ThrowExact for x86/funclets
  src/coreclr/vm/excep.cpp
  src/coreclr/vm/i386/asmhelpers.S
  src/coreclr/vm/i386/asmhelpers.asm
  src/coreclr/vm/jithelpers.cpp
Labels: area-async

#3083 [NativeAOT-LLVM] Do some pending post-merge tasks
  src/coreclr/jit/llvmlssa.cpp
  src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/__Finalizer.SingleThreaded.cs
  src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj
  src/tests/nativeaot/SmokeTests/HelloWasm/HelloWasm.cs
Labels: area-NativeAOT-LLVM

#3087 [NativeAOT-LLVM] Fix debug info for implicit byrefs
  src/coreclr/jit/llvmdebuginfo.cpp
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebugging.cs
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebugging.py
Labels: area-NativeAOT-LLVM

#3091 [NativeAOT-LLVM] Fix instance method handling in DI
  src/coreclr/jit/llvmdebuginfo.cpp
  src/tests/nativeaot/SmokeTests/HelloWasm/WasmDebugging.py
Labels: area-NativeAOT-LLVM
